ALTER TABLE InstructorCourse
	ADD CONSTRAINT FK_INSTRUCTOR_COURSE_COURSEID
	FOREIGN KEY(CourseId) REFERENCES Course(CourseId)

    ALTER TABLE InstructorCourse
	ADD CONSTRAINT FK_INSTRUCTOR_COURSE_INSTRUCTORID
	FOREIGN KEY(InstructorId) REFERENCES Instructor(InstructorId)